- name: git init configdir
  command: git init
  args:
    chdir: "{{ configdir }}"
    creates: "{{ configdir }}/.git"
  register: git_init
  become_user: "{{ pname }}"

- name: git set user name
  git_config:
    name: user.name
    value: "{{ pname }}"
    scope: local
    repo: "{{ configdir }}"
  become_user: "{{ pname }}"

- name: git set user email
  git_config:
    name: user.email
    value: "{{ pname }}@{{ ansible_fqdn }}"
    scope: local
    repo: "{{ configdir }}"
  become_user: "{{ pname }}"

- name: git create initial commit
  shell: "git --git-dir {{ configdir }}/.git --work-tree {{ configdir }} add {{ configfile }}; git commit --message='[Ansible] Initial commit'"
  args:
    chdir: "{{ configdir }}"
  become_user: "{{ pname }}"
  when: "git_init.stdout.find('skipped') == -1"

- name: check git status of configfile
  command: "git --git-dir {{ configdir }}/.git --work-tree {{ configdir }} status --porcelain {{ configfile }}"
  args:
    chdir: "{{ configdir }}"
    removes: "{{ configdir }}/{{ configfile }}"
  changed_when: False
  become_user: "{{ pname }}"
  register: git_status

- name: git create commit
  shell: "git --git-dir {{ configdir }}/.git --work-tree {{ configdir }} add {{ configfile }}; git --git-dir {{ configdir }}/.git --work-tree {{ configdir }} commit --message='[Ansible] commit config file'"
  become_user: "{{ pname }}"
  when: "git_status.stdout.find('M default.cfg') != -1"
