---
- name: install necessary packages for sopel
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - python3
    - ipython3
    - python3-feedparser

- name: make directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ pname }}"
    group: "{{ pname }}"
  with_items:
    - "{{ botdir }}"
    - "{{ moddir }}"
    - "{{ configdir }}"
    - "{{ custommoddir }}"

- name: checkout sopel from github
  git:
    repo: https://github.com/sopel-irc/sopel.git
    dest: "{{ botdir }}"
    accept_hostkey: yes
  become_user: '{{ pname }}'
  notify: restart sopel
  tags: sopel-irc

- name: make sopel.py executable
  file:
    path: "{{ botdir }}/sopel.py"
    owner: "{{ pname }}"
    group: "{{ pname }}"
    mode: 0744
  tags: sopel-irc

- name: checkout sopel-rss from github
  git:
    repo: https://github.com/f4bio/sopel-rss.git
    dest: "{{ moddir }}/sopel-rss"
    version: master
    accept_hostkey: yes
  become_user: "{{ pname }}"
  when: rss
  notify: restart sopel
  tags: sopel-rss

- name: link from custom module directory to rss.py
  file:
    dest: "{{ custommoddir }}/rss.py"
    src: "{{ moddir }}/sopel-rss/rss.py"
    state: link
  when: rss
  tags: sopel-rss

- name: check if config file exists
  stat:
    path: "{{ configdir }}/{{ configfile }}"
  register: sopelconfig
  tags: sopel-rss

- include: sopel-git.yml
  when: "{{ sopelconfig.stat.exists }}"
  tags: sopel-rss

- name: copy config
  template:
    dest: "{{ configdir }}/{{ configfile }}"
    src: default.cfg.j2
    owner: "{{ pname }}"
    group: "{{ pname }}"
    mode: 0644
  when: "not {{ sopelconfig.stat.exists }}"
  tags: sopel-rss

- name: start runit sopel
  command: sv start sopel
  when: "not {{ sopelconfig.stat.exists }}"
  tags: sopel-rss

- include: sopel-git.yml
  tags: sopel-rss
